Workflows:
  android-workflow:
    name: Android Debug Build

    scripts:
      - name: Grant permissions
        script: chmod +x ./gradlew

      - name: Build Debug APK with Force Refresh
        script: ./gradlew clean assembleDebug --refresh-dependencies --no-daemon

    artifacts:
      - app/build/outputs/apk/debug/*.apk

    publishing:
      email:
        recipients:
          - alywm100@gmail.com
