workflows:
  android-workflow:
    name: Android Debug Build

    scripts:
      - name: Grant permissions
        script: chmod +x ./gradlew

      - name: Clean project
        script: ./gradlew clean

      - name: Build Debug APK
        script: ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/apk/debug/*.apk

    publishing:
      email:
        recipients:
          - alywm100@gmail.com
